### ISSUE TITLE
Investigate kinect-daemon crash

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/emerge2016#1]
```
listening on http://localhost:8008
[Stream 70] Negotiated packet size 1920
write_register: 0x0105 <= 0x00
write_register: 0x0006 <= 0x00
write_register: 0x0012 <= 0x03
write_register: 0x0013 <= 0x01
write_register: 0x0014 <= 0x1e
write_register: 0x0006 <= 0x02
write_register: 0x0017 <= 0x00
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Context.EventEmitter.addListener (events.js:160:15)
    at Namespace.<anonymous> (/home/brannondorsey/Documents/work/Branger_Briz/emerge2016/installation/kinect-daemon/server.js:20:9)
    at Namespace.EventEmitter.emit (events.js:95:17)
    at Namespace.emit (/home/brannondorsey/Documents/work/Branger_Briz/emerge2016/installation/node_modules/socket.io/lib/namespace.js:206:10)
    at /home/brannondorsey/Documents/work/Branger_Briz/emerge2016/installation/node_modules/socket.io/lib/namespace.js:174:14
    at process._tickCallback (node.js:415:13)
```

**Comment by nbriz** [comment]
i also get this error on the kinect-daemon every once in a while ( usually the first time i launch the app after launching the daemon )

```
[Stream 70] Lost 152 total packets in 0 frames (inf lppf)
```

**Comment by nbriz** [comment]
&& also this one ( which shows up when the daemon's been running for a while && the app has been quit/launched numerous times )

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Context.EventEmitter.addListener (events.js:160:15)
    at Namespace.<anonymous> (/home/bbmac/PROJECTS/emerge2016/installation/kinect-daemon/server.js:20:9)
    at Namespace.EventEmitter.emit (events.js:95:17)
    at Namespace.emit (/home/bbmac/PROJECTS/emerge2016/installation/node_modules/socket.io/lib/namespace.js:206:10)
    at /home/bbmac/PROJECTS/emerge2016/installation/node_modules/socket.io/lib/namespace.js:174:14
    at process._tickCallback (node.js:415:13)
```

**Comment by brannondorsey** [comment]
Saw this one today too:

```
USB device disappeared, cancelling stream 82 :(
USB camera marked dead, stopping streams
write_register: 0x0006 <= 0x00
send_cmd: Output control transfer failed (-4)
write_register: send_cmd() returned -4
USB camera marked dead, stopping streams
USB camera marked dead, stopping streams
USB camera marked dead, stopping streams
USB camera marked dead, stopping streams
```

**Comment by nbriz** [comment]
We are now watching for these errors and relaunching the kinect daemon via `launch_and_poll_kinect_daemon.js`.
